### ISSUE TITLE
502 error on model pods

### ISSUE THREAD

**Issue by kirillmakhonin** [epam/legion#25]
1. When I started performance tests of test-summation model from Jenkins I got 502 error on 9/1000 requests.
2. Also I see some troubles on liara and edi backend server latency

Maybe this occurs because of current k8s overlay network.

**Comment by kirillmakhonin** [comment]
Problem detected: consul and nginx doesn't remove invalid model pods. Consul would be removed from stack (#18), but we also should configure nginx to automatically remove invalid pods from upstreams.

**Comment by akharlamov** [comment]
The issue is absolete as we do not use consul anymore.
