### ISSUE TITLE
Jenkins looses all its state on pod restart. 

### ISSUE THREAD

**Issue by akharlamov** [epam/legion#28]
At the moment Jenkins master stores all data inside container. As result, all state is lost on a pod migration or restart. 

1. Jenkins pod must bootstrap itself from information available inside Kubernetes, at least in regard of security credentials and basic configuration.

2. Workspaces should be stored on a separate volume which will survive simple issues.

**Comment by kirillmakhonin** [comment]
Has been merged into develop
