### ISSUE TITLE
Kops multiple node instance groups and auto-scaling

### ISSUE THREAD

**Issue by MaksymBilenko** [epam/legion#41]
Idea:
- Need to have regular light nodes for day to day activities
- Separate node group with `heavy` shape for model training that starts nodes only on demand once training pod scheduled

**Comment by kirillmakhonin** [comment]
We should be able to choose resources (RAM and CPU) instead of name of shape in Jenkinsfile.

**Comment by MaksymBilenko** [comment]
- [ ] Start new `heavy` instance on demand with resources -> ram/cpu
- [ ] Add tolerations to a instance groups to prevent non training containers not to prevent scale-down
- [ ] Add tolerations at jenkins plugin to allow jenkins slave to use `heavy` nodes
