### ISSUE TITLE
Support Multiple Read/Write and Exclusive RW volumes in K8S

### ISSUE THREAD

**Issue by akharlamov** [epam/legion#9]
We need to support exclusive read-write and share read-write volumes in K8S provisioned by legion scripts. For example, shared volume is needed for Airflow DAG sharing, and many pods including Consul and Jupyter need their own storage.

**Comment by akharlamov** [comment]
Assigned to @alexander-semenets as his PR with KOPS will likely cover this ticket too.

**Comment by kirillmakhonin** [comment]
Has been merged into develop
